"""add unique constraints to author name and book name/author_id

Revision ID: 4fe7bc45bc57
Revises: b3d5a4d441c4
Create Date: 2026-07-30 23:13:51.645399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe7bc45bc57'
down_revision: Union[str, Sequence[str], None] = 'b3d5a4d441c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_author_name', 'author', ['name'])
    op.create_unique_constraint('uq_book_name_author_id', 'book', ['name', 'author_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_book_name_author_id', 'book', type_='unique')
    op.drop_constraint('uq_author_name', 'author', type_='unique')
    # ### end Alembic commands ###
